apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 10.94.192.67:6379
  - name: redisPassword
    value: b3ab57d3-eb83-4c3d-87a4-cbc7a5161585
  - name: enableTLS
    value: false
  - name: maxRetries
    value: 3
  - name: maxRetryBackoff
    value: 2