apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.gcp.pubsub
  version: v1
  metadata:
  - name: type
    value: "service_account"
  - name: projectId
    value: "<project id>"
  - name: identityProjectId
    value: "<identity project id>"
  - name: privateKeyId
    value: "<private key id>"
  - name: clientEmail
    value: "<client email>"
  - name: clientId
    value: "client id"
  - name: authUri
    value: "https://accounts.google.com/o/oauth2/auth"
  - name: tokenUri
    value: "https://oauth2.googleapis.com/token"
  - name: authProviderX509CertUrl
    value: "https://www.googleapis.com/oauth2/v1/certs"
  - name: clientX509CertUrl
    value: "<client x509 cert url>"
  - name: privateKey
    value: "<private key>"
  - name: disableEntityManagement
    value: "false"
