apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: <host:port>
  - name: redisPassword
    value: <redis password>
  - name: enableTLS
    value: false
  - name: maxRetries
    value: 3
  - name: maxRetryBackoff
    value: 2